/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The container of the category\'s parent category, if the current category is a subcategory.
 * @export
 * @interface CategoryParent
 */
export interface CategoryParent {
    /**
     * The URL to access the parent category in a browser.
     * @type {string}
     * @memberof CategoryParent
     */
    'link': string;
    /**
     * The display name that identifies the parent category.
     * @type {string}
     * @memberof CategoryParent
     */
    'name': string;
    /**
     * The unique identifier to access the parent of the category resource.
     * @type {string}
     * @memberof CategoryParent
     */
    'uri': string;
}

