/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ChannelsModeratorsReplaceModeratorsRequest
 */
export interface ChannelsModeratorsReplaceModeratorsRequest {
    /**
     * The URI of the user to add as a moderator.
     * @type {string}
     * @memberof ChannelsModeratorsReplaceModeratorsRequest
     */
    'user_uri': string;
}

