/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The privacy settings of the channel.
 * @export
 * @interface ChannelPrivacy
 */
export interface ChannelPrivacy {
    /**
     * The privacy setting of the channel.  Option descriptions:  * `anybody` - Anyone can access the channel. This privacy setting appears as `Public` on the Vimeo front end.  * `moderators` - Only moderators can access the channel.  * `users` - Only registered users can access the channel. _This field is deprecated._ 
     * @type {string}
     * @memberof ChannelPrivacy
     */
    'view': ChannelPrivacyViewEnum;
}

type ChannelPrivacyViewEnum = 'anybody' | 'moderators' | 'users'


