/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EditUserRequestVideosPrivacy } from './edit-user-request-videos-privacy';

/**
 * 
 * @export
 * @interface EditUserRequestVideos
 */
export interface EditUserRequestVideos {
    /**
     * 
     * @type {EditUserRequestVideosPrivacy}
     * @memberof EditUserRequestVideos
     */
    'privacy'?: EditUserRequestVideosPrivacy;
}

