/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FragmentsMetadata } from './fragments-metadata';

/**
 * 
 * @export
 * @interface Fragments
 */
export interface Fragments {
    /**
     * The time in ISO 8601 format when the fragment was created.
     * @type {string}
     * @memberof Fragments
     */
    'created_on': string;
    /**
     * 
     * @type {FragmentsMetadata}
     * @memberof Fragments
     */
    'metadata': FragmentsMetadata;
    /**
     * The time in ISO 8601 format when the fragment was last updated.
     * @type {string}
     * @memberof Fragments
     */
    'modified_on': string;
    /**
     * The time in milliseconds of the fragment\'s _inpoint_, or the time from the start of the video that marks the beginning of the fragment.
     * @type {number}
     * @memberof Fragments
     */
    'timecode': number;
    /**
     * The URI of the video fragment.
     * @type {string}
     * @memberof Fragments
     */
    'uri': string;
}

