/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LiveEventVideosAddMultipleRequestVideosInner } from './live-event-videos-add-multiple-request-videos-inner';

/**
 * 
 * @export
 * @interface LiveEventVideosAddMultipleRequest
 */
export interface LiveEventVideosAddMultipleRequest {
    /**
     * An array of video objects.
     * @type {Array<LiveEventVideosAddMultipleRequestVideosInner>}
     * @memberof LiveEventVideosAddMultipleRequest
     */
    'videos'?: Array<LiveEventVideosAddMultipleRequestVideosInner>;
}

