/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LiveEmbedPrivacyEmbedEventOnDomainsRequest1
 */
export interface LiveEmbedPrivacyEmbedEventOnDomainsRequest1 {
    /**
     * An array of the domains on which the embedded event can appear.
     * @type {Array<string>}
     * @memberof LiveEmbedPrivacyEmbedEventOnDomainsRequest1
     */
    'allowed_domains'?: Array<string>;
}

