/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OnDemandPostersUpdatePosterRequest
 */
export interface OnDemandPostersUpdatePosterRequest {
    /**
     * Whether this poster is the one that appears on the On Demand page.
     * @type {boolean}
     * @memberof OnDemandPostersUpdatePosterRequest
     */
    'active'?: boolean;
}

