/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OnDemandPageEpisodesBuy } from './on-demand-page-episodes-buy';
import { OnDemandPageEpisodesRent } from './on-demand-page-episodes-rent';

/**
 * Information about the On Demand page\'s episodes, if the page is for a series.
 * @export
 * @interface OnDemandPageEpisodes
 */
export interface OnDemandPageEpisodes {
    /**
     * 
     * @type {OnDemandPageEpisodesBuy}
     * @memberof OnDemandPageEpisodes
     */
    'buy': OnDemandPageEpisodesBuy;
    /**
     * 
     * @type {OnDemandPageEpisodesRent}
     * @memberof OnDemandPageEpisodes
     */
    'rent': OnDemandPageEpisodesRent;
}

