/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The first and second colors of the On Demand page.
 * @export
 * @interface OnDemandPageColors
 */
export interface OnDemandPageColors {
    /**
     * The hexadecimal color code for the On Demand page\'s first color.
     * @type {string}
     * @memberof OnDemandPageColors
     */
    'primary': string;
    /**
     * The hexadecimal color code for the On Demand page\'s second color.
     * @type {string}
     * @memberof OnDemandPageColors
     */
    'secondary': string;
}

