/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OnDemandPromotionMetadataConnectionsCodes } from './on-demand-promotion-metadata-connections-codes';

/**
 * A list of resource URIs related to the promotion.
 * @export
 * @interface OnDemandPromotionMetadataConnections
 */
export interface OnDemandPromotionMetadataConnections {
    /**
     * 
     * @type {OnDemandPromotionMetadataConnectionsCodes}
     * @memberof OnDemandPromotionMetadataConnections
     */
    'codes': OnDemandPromotionMetadataConnectionsCodes;
}

