/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PictureSizesInner
 */
export interface PictureSizesInner {
    /**
     * The height of the picture.
     * @type {number}
     * @memberof PictureSizesInner
     */
    'height': number | null;
    /**
     * The direct link to the image file. For information about the format of the image file, see our [Working with Thumbnail Uploads](https://developer.vimeo.com/api/upload/thumbnails#returning-the-link-to-a-thumbnail) guide.
     * @type {string}
     * @memberof PictureSizesInner
     */
    'link': string;
    /**
     * The direct link to the image file with a play button overlay. For information about the format of the image file, see our [Working with Thumbnail Uploads](https://developer.vimeo.com/api/upload/thumbnails#returning-the-link-to-a-thumbnail) guide.
     * @type {string}
     * @memberof PictureSizesInner
     */
    'link_with_play_button'?: string;
    /**
     * The width of the picture.
     * @type {number}
     * @memberof PictureSizesInner
     */
    'width': number;
}

