/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PresetSettingsColors
 */
export interface PresetSettingsColors {
    /**
     * The fourth player color, which controls the player background color.
     * @type {string}
     * @memberof PresetSettingsColors
     */
    'color_four': string;
    /**
     * The first player color, which controls the color of the progress bar, buttons, and more.
     * @type {string}
     * @memberof PresetSettingsColors
     */
    'color_one': string;
    /**
     * The third player color, which controls the color of text and icons.
     * @type {string}
     * @memberof PresetSettingsColors
     */
    'color_three': string;
    /**
     * The second player color, which controls the player accent color.
     * @type {string}
     * @memberof PresetSettingsColors
     */
    'color_two': string;
}

