/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectMetadata } from './project-metadata';
import { ProjectPrivacy } from './project-privacy';
import { ProjectSettings } from './project-settings';
import { User } from './user';

/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * The access grant response that applies to the team member. _This field is deprecated because grants are no longer exposed via API responses._
     * @type {object}
     * @memberof Project
     */
    'access_grant': object;
    /**
     * The time in ISO 8601 format when the folder was created.
     * @type {string}
     * @memberof Project
     */
    'created_time': string;
    /**
     * The URI for the user who created the folder.
     * @type {string}
     * @memberof Project
     */
    'creator_uri': string;
    /**
     * Whether this folder has at least one subfolder.
     * @type {boolean}
     * @memberof Project
     */
    'has_subfolder': boolean;
    /**
     * Whether the folder is pinned.
     * @type {boolean}
     * @memberof Project
     */
    'is_pinned': boolean;
    /**
     * Whether the folder is a private-to-me folder for the user.
     * @type {boolean}
     * @memberof Project
     */
    'is_private_to_user': boolean;
    /**
     * The time in ISO 8601 format when a user last performed an action on the folder.
     * @type {string}
     * @memberof Project
     */
    'last_user_action_event_date': string | null;
    /**
     * The link to the folder on Vimeo.
     * @type {string}
     * @memberof Project
     */
    'link': string;
    /**
     * The link to the folder management page.
     * @type {string}
     * @memberof Project
     */
    'manage_link': string;
    /**
     * 
     * @type {ProjectMetadata}
     * @memberof Project
     */
    'metadata': ProjectMetadata;
    /**
     * The time in ISO 8601 format when the folder was last modified.
     * @type {string}
     * @memberof Project
     */
    'modified_time': string;
    /**
     * The name of the folder.
     * @type {string}
     * @memberof Project
     */
    'name': string;
    /**
     * The time in ISO 8601 format when the folder was pinned.
     * @type {string}
     * @memberof Project
     */
    'pinned_on': string | null;
    /**
     * 
     * @type {ProjectPrivacy}
     * @memberof Project
     */
    'privacy': ProjectPrivacy;
    /**
     * The resource key string of the folder.
     * @type {string}
     * @memberof Project
     */
    'resource_key': string;
    /**
     * 
     * @type {ProjectSettings}
     * @memberof Project
     */
    'settings': ProjectSettings;
    /**
     * The URI of the folder.
     * @type {string}
     * @memberof Project
     */
    'uri': string;
    /**
     * The owner of the folder.
     * @type {User}
     * @memberof Project
     */
    'user': User;
}

