/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the purchased product.
 * @export
 * @interface SubscriptionPlansMetadataPurchasedProduct
 */
export interface SubscriptionPlansMetadataPurchasedProduct {
    /**
     * The display price of the purchased product.
     * @type {number}
     * @memberof SubscriptionPlansMetadataPurchasedProduct
     */
    'display_price': number;
    /**
     * Whether the purchased product is billed as a monthly subscription.
     * @type {boolean}
     * @memberof SubscriptionPlansMetadataPurchasedProduct
     */
    'is_monthly': boolean;
}

