/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The list of entitlement parameters corresponding to the tier.
 * @export
 * @interface SubscriptionPlansMetadataEntitlementsParams
 */
export interface SubscriptionPlansMetadataEntitlementsParams {
    /**
     * The number of team seats included with the tier.
     * @type {string}
     * @memberof SubscriptionPlansMetadataEntitlementsParams
     */
    'team_seats': string | null;
    /**
     * The amount of video storage for the user\'s periodic quota.
     * @type {string}
     * @memberof SubscriptionPlansMetadataEntitlementsParams
     */
    'video_storage_periodic_quota': string | null;
    /**
     * The video storage total lifetime cap.
     * @type {string}
     * @memberof SubscriptionPlansMetadataEntitlementsParams
     */
    'video_storage_quota_cap': string | null;
    /**
     * The video storage quota period.  Option descriptions:  * `lifetime` - The product has a lifetime video storage quota period.  * `month` - The product has a monthly video storage quota period.  * `week` - The product has a weekly video storage quota period.  * `year` - The product has a yearly video storage quota period. 
     * @type {string}
     * @memberof SubscriptionPlansMetadataEntitlementsParams
     */
    'video_storage_quota_period': SubscriptionPlansMetadataEntitlementsParamsVideoStorageQuotaPeriodEnum;
    /**
     * The unit of the video storage for the user\'s periodic quota.  Option descriptions:  * `video_count` - The product has video storage based on video count.  * `video_size` - The product has video storage based on video size. 
     * @type {string}
     * @memberof SubscriptionPlansMetadataEntitlementsParams
     */
    'video_storage_quota_unit': SubscriptionPlansMetadataEntitlementsParamsVideoStorageQuotaUnitEnum;
}

type SubscriptionPlansMetadataEntitlementsParamsVideoStorageQuotaPeriodEnum = 'lifetime' | 'month' | 'week' | 'year'
type SubscriptionPlansMetadataEntitlementsParamsVideoStorageQuotaUnitEnum = 'video_count' | 'video_size'


