/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TeamRoleApplicablePermissionPolicies } from './team-role-applicable-permission-policies';

/**
 * 
 * @export
 * @interface TeamRole
 */
export interface TeamRole {
    /**
     * 
     * @type {TeamRoleApplicablePermissionPolicies}
     * @memberof TeamRole
     */
    'applicable_permission_policies'?: TeamRoleApplicablePermissionPolicies;
    /**
     * The total number of team members with this role.
     * @type {number}
     * @memberof TeamRole
     */
    'count'?: number;
    /**
     * The translated display description of the role.
     * @type {string}
     * @memberof TeamRole
     */
    'display_description'?: string;
    /**
     * The translated display name of the role.
     * @type {string}
     * @memberof TeamRole
     */
    'display_name'?: string;
    /**
     * The untranslated role of the user who made the request.  Option descriptions:  * `Admin` - The team member has admin permissions. They can upload and edit videos for the entire team and perform team administration tasks.  * `Contributor` - The team member has contributor permissions. They can upload and edit videos for the entire team but can’t perform team administration tasks.  * `Contributor Plus` - The team member has contributor-plus permissions. They can upload and edit videos for the entire team and have additional sets of permissions but can\'t perform team administration tasks.  * `Owner` - The team member has owner permissions.  * `Uploader` - The team member has uploader permissions. They can upload videos for the entire team but can\'t edit videos.  * `Viewer` - The team member has viewer permissions. They can access team videos and specific team folders but can\'t upload or edit videos. 
     * @type {string}
     * @memberof TeamRole
     */
    'permission_level': TeamRolePermissionLevelEnum;
    /**
     * The untranslated role of the user who made the request.  Option descriptions:  * `Admin` - The team member has admin permissions. They can upload and edit videos for the entire team and perform team administration tasks.  * `Contributor` - The team member has contributor permissions. They can upload and edit videos for the entire team but can’t perform team administration tasks.  * `Contributor Plus` - The team member has contributor-plus permissions. They can upload and edit videos for the entire team and have additional sets of permissions but can\'t perform team administration tasks.  * `Owner` - The team member has owner permissions.  * `Uploader` - The team member has uploader permissions. They can upload videos for the entire team but can’t edit videos.  * `Viewer` - The team member has viewer permissions. They can access team videos and specific team folders but can’t upload or edit videos. 
     * @type {string}
     * @memberof TeamRole
     */
    'role': TeamRoleRoleEnum;
    /**
     * The unique identifier to access the team role.
     * @type {string}
     * @memberof TeamRole
     */
    'uri': string;
}

type TeamRolePermissionLevelEnum = 'Admin' | 'Contributor' | 'Contributor Plus' | 'Owner' | 'Uploader' | 'Viewer'
type TeamRoleRoleEnum = 'Admin' | 'Contributor' | 'Contributor Plus' | 'Owner' | 'Uploader' | 'Viewer'


