/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A standard connection object indicating how to get the owner of this user.
 * @export
 * @interface TeamMembershipMetadataConnectionsOwner
 */
export interface TeamMembershipMetadataConnectionsOwner {
    /**
     * The display name of the team owner.
     * @type {string}
     * @memberof TeamMembershipMetadataConnectionsOwner
     */
    'display_name': string;
    /**
     * The team owner\'s email address.
     * @type {string}
     * @memberof TeamMembershipMetadataConnectionsOwner
     */
    'email': string;
    /**
     * The total number of remaining team member invites.
     * @type {number}
     * @memberof TeamMembershipMetadataConnectionsOwner
     */
    'invites_remaining': number;
    /**
     * An array of HTTP methods permitted on this URI.
     * @type {Array<string>}
     * @memberof TeamMembershipMetadataConnectionsOwner
     */
    'options': Array<string>;
    /**
     * The total number of owners on this connection.
     * @type {number}
     * @memberof TeamMembershipMetadataConnectionsOwner
     */
    'total': number;
    /**
     * The total number of team members for the specified team owner.
     * @type {number}
     * @memberof TeamMembershipMetadataConnectionsOwner
     */
    'total_members': number;
    /**
     * The API URI that resolves to the connection data.
     * @type {string}
     * @memberof TeamMembershipMetadataConnectionsOwner
     */
    'uri': string;
}

