/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about whether a user can view the team members associated with a video.
 * @export
 * @interface VideoMetadataInteractionsViewTeamMembers
 */
export interface VideoMetadataInteractionsViewTeamMembers {
    /**
     * An array of HTTP methods permitted on this URI.
     * @type {Array<string>}
     * @memberof VideoMetadataInteractionsViewTeamMembers
     */
    'options': Array<string>;
    /**
     * The API URI that resolves to the connection data.
     * @type {string}
     * @memberof VideoMetadataInteractionsViewTeamMembers
     */
    'uri': string;
}

