/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The video\'s Vimeo On Demand information.
 * @export
 * @interface VideoVod
 */
export interface VideoVod {
    /**
     * The video\'s Vimeo On Demand ID.
     * @type {number}
     * @memberof VideoVod
     */
    'id': number | null;
}

