/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about whether this video appears on the user\'s Watch Later list.
 * @export
 * @interface VideoMetadataInteractionsWatchlater
 */
export interface VideoMetadataInteractionsWatchlater {
    /**
     * Whether the user has added the video to their Watch Later list.
     * @type {boolean}
     * @memberof VideoMetadataInteractionsWatchlater
     */
    'added': boolean;
    /**
     * The time in ISO 8601 format when the user added the video to their Watch Later list.
     * @type {string}
     * @memberof VideoMetadataInteractionsWatchlater
     */
    'added_time': string;
    /**
     * An array of HTTP methods permitted on this URI.
     * @type {Array<string>}
     * @memberof VideoMetadataInteractionsWatchlater
     */
    'options': Array<string>;
    /**
     * The API URI that resolves to the connection data.
     * @type {string}
     * @memberof VideoMetadataInteractionsWatchlater
     */
    'uri': string;
}

