/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VideosUploadsBeginVideoUploadProcessRequestSpatialDirectorTimelineInner } from './videos-uploads-begin-video-upload-process-request-spatial-director-timeline-inner';

/**
 * 
 * @export
 * @interface VideosUploadsBeginVideoUploadProcessRequestSpatial
 */
export interface VideosUploadsBeginVideoUploadProcessRequestSpatial {
    /**
     * An array representing the 360 director timeline.
     * @type {Array<VideosUploadsBeginVideoUploadProcessRequestSpatialDirectorTimelineInner>}
     * @memberof VideosUploadsBeginVideoUploadProcessRequestSpatial
     */
    'director_timeline'?: Array<VideosUploadsBeginVideoUploadProcessRequestSpatialDirectorTimelineInner>;
    /**
     * The 360 field of view. This value must be between `30` and `90`; the default value is `50`.
     * @type {number}
     * @memberof VideosUploadsBeginVideoUploadProcessRequestSpatial
     */
    'field_of_view'?: number;
    /**
     * The 360 spatial projection.  Option descriptions:  * `cubical` - Use cubical projection.  * `cylindrical` - Use cylindrical projection.  * `dome` - Use dome projection.  * `equirectangular` - Use equirectangular projection.  * `pyramid` - Use pyramid projection. 
     * @type {string}
     * @memberof VideosUploadsBeginVideoUploadProcessRequestSpatial
     */
    'projection'?: VideosUploadsBeginVideoUploadProcessRequestSpatialProjectionEnum;
    /**
     * The 360 spatial stereo format.  Option descriptions:  * `left-right` - Use left-right stereo.  * `mono` - Use monaural audio.  * `top-bottom` - Use top-bottom stereo. 
     * @type {string}
     * @memberof VideosUploadsBeginVideoUploadProcessRequestSpatial
     */
    'stereo_format'?: VideosUploadsBeginVideoUploadProcessRequestSpatialStereoFormatEnum;
}

type VideosUploadsBeginVideoUploadProcessRequestSpatialProjectionEnum = 'cubical' | 'cylindrical' | 'dome' | 'equirectangular' | 'pyramid'
type VideosUploadsBeginVideoUploadProcessRequestSpatialStereoFormatEnum = 'left-right' | 'mono' | 'top-bottom'


