/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

The version of the OpenAPI document: 3.4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarEvent } from './webinar-event';

/**
 * The details of the webinar events associated with the webinar.
 * @export
 * @interface WebinarEvents
 */
export interface WebinarEvents {
    /**
     * The details of the first page of webinar events associated with the webinar.
     * @type {Array<WebinarEvent>}
     * @memberof WebinarEvents
     */
    'data': Array<WebinarEvent>;
    /**
     * The total number of webinar events associated with the webinar.
     * @type {number}
     * @memberof WebinarEvents
     */
    'total': number;
}

